mainApp/urls.py
from django.urls import path
from .views import *

app_name = 'mainApp'

urlpatterns = [
    path('',mainPage,name='mainApp'),
]

price_app/urls.py
from django.urls import path
from .views import *

app_name = 'price_app'

urlpatterns = [
    path('price-prediction/',price,name='priceApp'),
]

tomato/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mainApp.urls')),
    path('',include('tomato_disease_recognition_app.urls')),
    path('',include('price_app.urls')),
    path('',include('tomato_disease_info_app.urls')),
    path('',include('tomato_site_info.urls')),
]

tomato_disease_info_app/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_view
app_name = 'tomato_disease_info_app'

urlpatterns = [
    path('tomato_disease_info/', disease_info, name='tomato_disease_info'),
    path('tomato_disease_info/info_page/', info_page, name='info' ),
    path('tomato_disease_info/info_page/2', info_page2, name='info2' ),
    path('tomato_disease_info/info_page/3', info_page3, name='info3' ),
    path('tomato_disease_info/info_page/4', info_page4, name='info4' ),
    path('tomato_disease_info/info_page/5', info_page5, name='info5' ),
    path('tomato_disease_info/info_page/6', info_page6, name='info6' ),
    path('tomato_disease_info/info_page/7', info_page7, name='info7' ),
    path('tomato_disease_info/info_page/8', info_page8, name='info8' ),

    
]

tomato_disease_recognition_app/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_view
app_name = 'tomato_disease_recognition_app'

urlpatterns = [
    path('tomato_disease_recognition/',tomato_disease_recogntion_page,name='tomato_disease_recognition'),

]

tomato_site_info/urls.py
from django.urls import path
from .views import *
from django.contrib.auth import views as auth_view

app_name='tomato_site_info'
urlpatterns=[
    path('tomato_site_info/', tomato_site_info, name='tomato_site_info'),
]

mainApp/models.py
from django.db import models

# Create your models here.

mainApp/views.py
from django.shortcuts import render

# Create your views here.
def mainPage(request):
    return render(request,'main.html')

mainApp/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href='{% static "mainApp/css/reset.css" %}'>
    <link rel="stylesheet" href='{% static "mainApp/css/base.css" %}'>
    {% block csslist %}{% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <header>
        <nav>
            <ul class="navigation">
                <!-- <li class="logo"><a href="{% url 'mainApp:mainApp' %}"><img src="{% static 'images/logo_no_background.png' %}" alt=""></a></li> -->
                <ol class="menu-li">
                    <li id="open"><a href="#">▼</a></li>
                    <li><a href="{% url 'tomato_disease_recognition_app:tomato_disease_recognition' %}">토마토 질병인식</a></li>
                    <li><a href="{% url 'price_app:priceApp' %}">토마토 가격예측</a></li>
                    <li><a href="{% url 'tomato_disease_info_app:tomato_disease_info' %}">토마토 질병도감</a></li>
                    <li><a href="{% url 'tomato_site_info:tomato_site_info' %}">사이트 설명</a></li>
                </ol>
            </ul>
        </nav>
    </header>

    <main align="center">
        {% block content %}
          
        {% endblock %}
    </main>

    <footer>

    </footer>
    <script src="{% static 'mainApp/js/base.js' %}"></script>
</body>
</html>

mainApp/templates/main.html
{% extends 'base.html' %}
{% load static %}
{% block csslist %}
<link rel="stylesheet" href='{% static "mainApp/css/main.css" %}'>
{% endblock %}

{% block title %}메인{% endblock %}

{% block content %}

<div class="main-screen-board">
    <div class='main-screen-text'>
        <span>당신의 토마토는 어떤가요?<br><br>건강한가요?</span>
        <br><br><br>
        <div class="blank"></div>
        <div class="next_url"><a href="{% url 'tomato_disease_recognition_app:tomato_disease_recognition' %}">지금 알아보러가기</a></div>
    </div>
</div>


{% endblock %}